name: myutils
description: "A new Flutter project."

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  common_resource:
    path: ../resources/common_resource
  dayoneasia:
    path: ../..
  cupertino_icons: ^1.0.6
  flutter_svg: any
  go_router: ^14.2.3
  app_settings: ^5.1.1
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.1.1
  path_provider: ^2.0.14
  flutter_image_gallery_saver: ^0.0.2
#  image_gallery_saver: ^2.0.3
#  flutter_gif: ^0.0.4

  #  intl:
#  syncfusion_flutter_datepicker: ^24.2.7
  easy_localization: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_bloc: ^8.1.3
#  collection: any
  rxdart: ^0.27.7
  equatable: ^2.0.5
  dio: ^5.3.3
  flutter_dotenv: ^5.0.2
  flutter_html: any
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.18.4
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.1.12
  cached_network_image: ^3.2.3
  lottie: ^3.1.0
  fluttertoast: ^8.2.8
  logger: ^2.4.0
  photo_manager: ^3.2.2
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  carousel_slider: ^5.0.0
  permission_handler: ^10.2.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  floating_draggable_widget: ^2.1.5
  device_info_plus: ^11.2.1
  translator: ^1.0.0
  expandable_page_view: ^1.0.17
  flutter_pdfview: ^1.3.2
#  draggable_float_widget: ^0.1.0
  network_info_plus: ^6.1.2
  pretty_dio_logger: ^1.4.0
  flutter_local_notifications: ^17.2.4
  googleapis_auth: ^1.6.0
  convex_bottom_bar: ^3.2.0

  flutter_widget_from_html: ^0.15.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.myutils
    iosBundleIdentifier: com.example.myutils
