// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Kw7RsvaLiR8NF4f8vYOHygxqW_3PtX4',
    appId: '1:982652917651:web:fe92b6e107554d6a273a66',
    messagingSenderId: '982652917651',
    projectId: 'sunnydayspiano',
    authDomain: 'sunnydayspiano.firebaseapp.com',
    storageBucket: 'sunnydayspiano.appspot.com',
    measurementId: 'G-FW5Q9CCKLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzsFhyREeKChJ6JVmdZDlk-ezGkhxA1qI',
    appId: '1:982652917651:android:e2a301e959d5b91c273a66',
    messagingSenderId: '982652917651',
    projectId: 'sunnydayspiano',
    storageBucket: 'sunnydayspiano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGf-tqF4FuvNAyqhsvDy5kFBeMUuWIQt8',
    appId: '1:982652917651:ios:91d564ae7f84a7fe273a66',
    messagingSenderId: '982652917651',
    projectId: 'sunnydayspiano',
    storageBucket: 'sunnydayspiano.appspot.com',
    iosBundleId: 'com.sunnydays.piano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGf-tqF4FuvNAyqhsvDy5kFBeMUuWIQt8',
    appId: '1:982652917651:ios:7720043e189da923273a66',
    messagingSenderId: '982652917651',
    projectId: 'sunnydayspiano',
    storageBucket: 'sunnydayspiano.appspot.com',
    iosBundleId: 'com.example.dayoneasia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Kw7RsvaLiR8NF4f8vYOHygxqW_3PtX4',
    appId: '1:982652917651:web:0529afb46b0f84ff273a66',
    messagingSenderId: '982652917651',
    projectId: 'sunnydayspiano',
    authDomain: 'sunnydayspiano.firebaseapp.com',
    storageBucket: 'sunnydayspiano.appspot.com',
    measurementId: 'G-L2TV95E1YH',
  );
}
